# Help: rename the adject docker-compose.override.example.yml file to docker-compose.override.yml
#       then in the override file uncomment the environment tag for the collectors you want to
#       run. Then add the environment vars you want to use.
version: '3.7'
services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "/mnt/data/HygieiaData:/data/db"
    restart: always

  db-setup:
    build: db
    depends_on:
      - db

  api:
    build: api
    image: hygieia-api
    depends_on:
      - db-setup
    ports:
      - "9080:8080"
    volumes:
      - "/mnt/data/HygieiaLogs:/hygieia/logs"
    restart: always

  api-audit:
    build: api-audit
    image: hygieia-api-audit
    depends_on:
      - db-setup
    ports:
      - "8081:8080"
    volumes:
      - "/mnt/data/HygieiaLogs:/hygieia/logs"
    restart: always

  ui:
    build: UI
    image: hygieia-ui
    depends_on:
      - api
    ports:
      - "3000:80"
    volumes:
      - "/mnt/data/HygieiaLogs:/hygieia/logs"
    restart: always

  jenkins-build-collector:
    build: collectors/build/jenkins
    image: hygieia-jenkins-build-collector
    volumes:
      - "/mnt/data/HygieiaLogs:/hygieia/logs"
    depends_on:
      - db-setup
    restart: always

  #jenkins-codequality-collector:
  #  build: collectors/build/jenkins-codequality
  #  image: hygieia-jenkins-codequality-collector
  #  depends_on:
  #    - db-setup

 # nexus-iq-collector:
  #  build: collectors/library-policy/nexus-iq-collector
  #  image: hygieia-nexus-iq-collector
  #  depends_on:
  #    - db-setup

  sonar-codequality-collector:
    build: collectors/build/sonar
    image: hygieia-sonar-codequality-collector
    volumes:
      - "/mnt/data/HygieiaLogs:/hygieia/logs"
    depends_on:
      - db-setup
    restart: always

  subversion-collector:
    build: collectors/scm/subversion
    image: hygieia-subversion-scm-collector
    volumes:
      - "/mnt/data/HygieiaLogs:/hygieia/logs"
    depends_on:
      - db-setup
    restart: always

  score-collector:
    build: collectors/misc/score
    image: hygieia-score-collector
    volumes:
      - "/mnt/data/HygieiaLogs:/hygieia/logs"
    depends_on:
      - db-setup
    restart: always

#volumes:
#  db-data:/mnt/data/HygieiaData
 # certs:
